# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-06 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurants_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='RestaurantsLocations',
        ),
    ]
