# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20181006_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
