# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantslocations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
