# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20181007_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantslocations',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
