# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20181008_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantslocations',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
